module.exports = {
  reactStrictMode: true,
  env: {
    REACT_APP_FIREBASE_KEY: process.env.REACT_APP_FIREBASE_KEY,
    REACT_APP_FIREBASE_DOMAIN: process.env.REACT_APP_FIREBASE_DOMAIN,
    REACT_APP_FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
    REACT_APP_FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
    REACT_APP_FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
    REACT_APP_FIREBASE_SENDER_ID: process.env.REACT_APP_FIREBASE_SENDER_ID,
  },
};
